### ISSUE TITLE
Word Search doesn't work for latest version of Alfred (4.6.7 [1305])

### ISSUE THREAD

**Issue by AristoSocrates** [jun6lee/Alfred-WordSearch#2]
Hi,
Like the most recent post about this issue, I'm finding that it no longer works for me. This is one of my most used Workflows so it's a big hit to my productivity and would appreciate your help.

I deleted the Workflow and re-installed it via the link provided (https://github.com/jun6lee/Alfred-WordSearch) but the issue persists. I don't know much about coding so I didn't know where to go from there.

FYI, I'm using a Mac Mini 2018 with macOS Monterey 12.4 and it has no issues for anything else.

As the previous post showed, when I type "syn" followed by a word, there are no results. I ran it through troubleshooting and this is the result: 

[18:45:55.217] Word Search[Script Filter] Queuing argument ''
[18:45:55.225] Word Search[Script Filter] Script with argv '(null)' finished
[18:45:55.226] ERROR: Word Search[Script Filter] Code 1: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
[18:45:55.968] Word Search[Script Filter] Queuing argument 'd'
[18:45:56.037] Word Search[Script Filter] Script with argv '(null)' finished
[18:45:56.039] ERROR: Word Search[Script Filter] Code 1: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
[18:45:56.296] Word Search[Script Filter] Queuing argument 'do'
[18:45:56.366] Word Search[Script Filter] Script with argv '(null)' finished
[18:45:56.367] ERROR: Word Search[Script Filter] Code 1: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
[18:45:56.409] Word Search[Script Filter] Queuing argument 'doo'
[18:45:56.478] Word Search[Script Filter] Script with argv '(null)' finished
[18:45:56.479] ERROR: Word Search[Script Filter] Code 1: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
[18:45:56.529] Word Search[Script Filter] Queuing argument 'door'
[18:45:56.533] Word Search[Script Filter] Script with argv '(null)' finished
[18:45:56.535] ERROR: Word Search[Script Filter] Code 1: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

Please let me know how to fix this (bearing in mind I'm naive to coding).

Thanks!

**Comment by AristoSocrates** [comment]
Hi Isaac, I contacted Alfred support and they said this has to do with Python 2 no longer being supported by MacOS Monterey 12.3... they said it was updated in this post (https://github.com/alfredapp/updated-third-party-python2-workflows#readme).

However, I'm still having the same exact issue - is there a simple fix for this or is this more complicated to fix?

**Comment by AristoSocrates** [comment]
UPDATE:
I re-installed Python 2 and faced a different issue. The troubleshooting log shows: 

[13:55:12.949] Logging Started...
[13:55:17.650] Word Search[Script Filter] Queuing argument 's'
[13:55:17.810] Word Search[Script Filter] Queuing argument 'se'
[13:55:17.938] Word Search[Script Filter] Queuing argument 'sea'
[13:55:18.035] Word Search[Script Filter] Script with argv '(null)' finished
[13:55:18.037] ERROR: Word Search[Script Filter] Code 1: .
13:55:17 workflow.py:2061 DEBUG    ---------- Word Search (1.0.0) ----------
13:55:17 workflow.py:1468 DEBUG    reading settings from /Users/tde/Library/Application Support/Alfred/Workflow Data/me.isaacpz/settings.json
13:55:17 workflow.py:2338 INFO     checking for update ...
13:55:17 background.py:230 DEBUG    [__workflow_update_check] command cached: /Users/tde/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/me.isaacpz/__workflow_update_check.argcache
13:55:17 background.py:234 DEBUG    [__workflow_update_check] passing job to background runner: [u'python', '/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/background.pyc', u'__workflow_update_check']
.
13:55:17 workflow.py:2061 DEBUG    ---------- Word Search (1.0.0) ----------
13:55:17 background.py:240 DEBUG    [__workflow_update_check] background job started
13:55:18 workflow.py:2080 ERROR    <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
Traceback (most recent call last):
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/workflow.py", line 2073, in run
    func(self)
  File "similar.py", line 15, in main
    words = wf.cached_data(args[0] + "_" + args[1], cacheSearch, max_age=60)
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/workflow3.py", line 659, in cached_data
    return super(Workflow3, self).cached_data(name, data_func, max_age)
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/workflow.py", line 1701, in cached_data
    data = data_func()
  File "similar.py", line 13, in cacheSearch
    return getSimilar(args[0], args[1])
  File "similar.py", line 32, in getSimilar
    r = web.get(url, params)
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/web.py", line 603, in get
    stream=stream)
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/web.py", line 591, in request
    return Response(req, stream)
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/web.py", line 239, in __init__
    self.raw = urllib2.urlopen(request)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
13:55:18 workflow.py:2103 DEBUG    ---------- finished in 0.288s ----------
[13:55:18.040] Word Search[Script Filter] {
  "items": [
    {
      "valid": false,
      "subtitle": "<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>",
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      },
      "title": "Error in workflow 'Word Search'"
    }
  ]
}
[13:55:18.057] Word Search[Script Filter] Queuing argument 'sear'
[13:55:18.281] Word Search[Script Filter] Queuing argument 'searc'
[13:55:18.355] Word Search[Script Filter] Queuing argument 'search'
[13:55:18.456] Word Search[Script Filter] Script with argv '(null)' finished
[13:55:18.460] ERROR: Word Search[Script Filter] Code 1: .
13:55:18 workflow.py:2061 DEBUG    ---------- Word Search (1.0.0) ----------
13:55:18 workflow.py:1468 DEBUG    reading settings from /Users/tde/Library/Application Support/Alfred/Workflow Data/me.isaacpz/settings.json
13:55:18 workflow.py:2338 INFO     checking for update ...
13:55:18 background.py:230 DEBUG    [__workflow_update_check] command cached: /Users/tde/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/me.isaacpz/__workflow_update_check.argcache
13:55:18 background.py:234 DEBUG    [__workflow_update_check] passing job to background runner: [u'python', '/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/background.pyc', u'__workflow_update_check']
.
13:55:18 workflow.py:2061 DEBUG    ---------- Word Search (1.0.0) ----------
13:55:18 background.py:240 DEBUG    [__workflow_update_check] background job started
13:55:18 workflow.py:2080 ERROR    <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
Traceback (most recent call last):
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/workflow.py", line 2073, in run
    func(self)
  File "similar.py", line 15, in main
    words = wf.cached_data(args[0] + "_" + args[1], cacheSearch, max_age=60)
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/workflow3.py", line 659, in cached_data
    return super(Workflow3, self).cached_data(name, data_func, max_age)
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/workflow.py", line 1701, in cached_data
    data = data_func()
  File "similar.py", line 13, in cacheSearch
    return getSimilar(args[0], args[1])
  File "similar.py", line 32, in getSimilar
    r = web.get(url, params)
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/web.py", line 603, in get
    stream=stream)
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/web.py", line 591, in request
    return Response(req, stream)
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/web.py", line 239, in __init__
    self.raw = urllib2.urlopen(request)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
13:55:18 workflow.py:2103 DEBUG    ---------- finished in 0.316s ----------
[13:55:18.463] Word Search[Script Filter] {
  "items": [
    {
      "valid": false,
      "subtitle": "<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>",
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      },
      "title": "Error in workflow 'Word Search'"
    }
  ]
}
[13:55:18.853] Word Search[Script Filter] Script with argv '(null)' finished
[13:55:18.856] ERROR: Word Search[Script Filter] Code 1: .
13:55:18 workflow.py:2061 DEBUG    ---------- Word Search (1.0.0) ----------
13:55:18 workflow.py:1468 DEBUG    reading settings from /Users/tde/Library/Application Support/Alfred/Workflow Data/me.isaacpz/settings.json
13:55:18 workflow.py:2338 INFO     checking for update ...
13:55:18 background.py:230 DEBUG    [__workflow_update_check] command cached: /Users/tde/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/me.isaacpz/__workflow_update_check.argcache
13:55:18 background.py:234 DEBUG    [__workflow_update_check] passing job to background runner: [u'python', '/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/background.pyc', u'__workflow_update_check']
.
13:55:18 workflow.py:2061 DEBUG    ---------- Word Search (1.0.0) ----------
13:55:18 background.py:240 DEBUG    [__workflow_update_check] background job started
13:55:18 workflow.py:2080 ERROR    <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
Traceback (most recent call last):
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/workflow.py", line 2073, in run
    func(self)
  File "similar.py", line 15, in main
    words = wf.cached_data(args[0] + "_" + args[1], cacheSearch, max_age=60)
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/workflow3.py", line 659, in cached_data
    return super(Workflow3, self).cached_data(name, data_func, max_age)
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/workflow.py", line 1701, in cached_data
    data = data_func()
  File "similar.py", line 13, in cacheSearch
    return getSimilar(args[0], args[1])
  File "similar.py", line 32, in getSimilar
    r = web.get(url, params)
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/web.py", line 603, in get
    stream=stream)
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/web.py", line 591, in request
    return Response(req, stream)
  File "/Users/tde/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A7AD319-3ECE-46CE-A7F1-9270A1461FCC/workflow/web.py", line 239, in __init__
    self.raw = urllib2.urlopen(request)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
13:55:18 workflow.py:2103 DEBUG    ---------- finished in 0.294s ----------
[13:55:18.859] Word Search[Script Filter] {
  "items": [
    {
      "valid": false,
      "subtitle": "<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>",
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      },
      "title": "Error in workflow 'Word Search'"
    }
  ]
}

**Comment by AristoSocrates** [comment]
**### ISSUE FIXED!**

Steps:
1. Re-install Python 2 via their website (https://www.python.org/downloads/release/python-2718/)
2. Follow the steps here to fix the Certificate issue (https://www.dev2qa.com/how-to-fix-python-error-certificate-verify-failed-unable-to-get-local-issuer-certificate-in-mac-os/)
3. Restart Alfred
